name: Main demo
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: List files in the repository
        run: java src/p1_capstone/p1capstone.java
            
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Run tests with Maven
        run: mvn -B p1capstoneTest.java --file pom.xml
